In [3]:
import numpy as np

In [4]:
import pandas as pd

In [20]:
l = [1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]


In [21]:
s1 = pd.Series(data = l)
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [22]:
s2 = pd.Series(data = l, index = ['a','b','c','d','e'])
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [23]:
print(type(l))
print(type(s1))
print(type(s2))

<class 'list'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [50]:
s3 = np.random.rand(5,4)
print(s3)

[[0.99450646 0.62057603 0.75215003 0.07494241]
 [0.57270864 0.36334087 0.73299456 0.47802551]
 [0.71392812 0.1521094  0.80587663 0.82161488]
 [0.49192644 0.03657638 0.10471204 0.01717536]
 [0.22834252 0.55228073 0.9044926  0.68643899]]


In [53]:
s4 = pd.DataFrame(data = s3)
print(s4)

          0         1         2         3
0  0.994506  0.620576  0.752150  0.074942
1  0.572709  0.363341  0.732995  0.478026
2  0.713928  0.152109  0.805877  0.821615
3  0.491926  0.036576  0.104712  0.017175
4  0.228343  0.552281  0.904493  0.686439


In [52]:
s5 = pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'],['w','x','y','z'])
print(s5)

          w         x         y         z
a  1.604315 -1.298266  1.319435 -0.502336
b  0.727919  2.074492  1.735363  0.130672
c -0.213580  0.134152 -1.577397  0.380436
d  0.979277 -0.172227 -1.152976 -1.279026
e  0.609393  1.011215 -2.547640  0.074165


In [55]:
s5.w['a']

1.60431505640834

In [58]:
s5[['w','x']]

w         x
a  1.604315 -1.298266
b  0.727919  2.074492
c -0.213580  0.134152
d  0.979277 -0.172227
e  0.609393  1.011215

In [60]:
print(s5.loc["a"])

w    1.604315
x   -1.298266
y    1.319435
z   -0.502336
Name: a, dtype: float64


In [63]:
print(s5.iloc[0])

w    1.604315
x   -1.298266
y    1.319435
z   -0.502336
Name: a, dtype: float64


In [69]:
s6 = s5[s5>0]
print(s6)

          w         x         y         z
a  1.604315       NaN  1.319435       NaN
b  0.727919  2.074492  1.735363  0.130672
c       NaN  0.134152       NaN  0.380436
d  0.979277       NaN       NaN       NaN
e  0.609393  1.011215       NaN  0.074165


/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1595: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1596: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1596: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


In [72]:
s7 = s5.drop('a')
print(s7)

          w         x         y         z
b  0.727919  2.074492  1.735363  0.130672
c -0.213580  0.134152 -1.577397  0.380436
d  0.979277 -0.172227 -1.152976 -1.279026
e  0.609393  1.011215 -2.547640  0.074165


In [78]:
s8 = s5.drop('a', axis = 0, inplace = False)
print(s8)

          w         x         y         z
b  0.727919  2.074492  1.735363  0.130672
c -0.213580  0.134152 -1.577397  0.380436
d  0.979277 -0.172227 -1.152976 -1.279026
e  0.609393  1.011215 -2.547640  0.074165


In [82]:
s9 = s5.drop('w', axis = 1, inplace = True)
print(s9)

None


In [93]:
#Dropping missing values
d={'A':[1,2,np.NaN], 'B':[1,np.NaN,np.NaN],'C':[1,2,3]}
# np.NaN is the missing element in DataFrame
df5=pd.DataFrame(d)
print(df5)
a = df5.dropna()       #drop any row with missing value
print(a)
b = df5.dropna(axis=1) #drop column with NULL value
print(b)
c = df5.dropna(thresh=2) #Require <2 non-NA values to drop row.
print(c)

     A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  NaN  3
     A    B  C
0  1.0  1.0  1
   C
0  1
1  2
2  3
     A    B  C
0  1.0  1.0  1
1  2.0  NaN  2


/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1595: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1596: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1596: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1595: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1596: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any(

In [103]:
#Dropping missing values
d={'A':[1,2,np.NaN], 'B':[1,np.NaN,np.NaN],'C':[1,2,3]}
# np.NaN is the missing element in DataFrame
df5=pd.DataFrame(d)
print(df5)
a = df5.fillna(0)       #drop any row with missing value
print(a)

     A    B  C
0  1.0  1.0  1
1  2.0  NaN  2
2  NaN  NaN  3
     A    B  C
0  1.0  1.0  1
1  2.0  0.0  2
2  0.0  0.0  3


/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1595: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1596: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/home/u204854/.local/lib/python3.9/site-packages/pandas/io/formats/format.py:1596: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


In [99]:
pd.read_csv("test1.csv")

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]