In [1]:
import numpy as np
from scipy.linalg import lu

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

Z,L,U = lu(A)

print(L)
print()
print(U)

[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]


In [3]:
import numpy as np
A = np.random.rand(3,3)
Q,R = np.linalg.qr(A)
print(A)
print()
print(Q)
print()
print(R)

[[0.83577878 0.23862286 0.50837871]
 [0.72051849 0.94882241 0.80375371]
 [0.9617494  0.2422171  0.58183219]]

[[-0.5709752   0.29839693 -0.76481801]
 [-0.49223335 -0.8700116   0.02803836]
 [-0.65703398  0.39247814  0.64363597]]

[[-1.46377422 -0.76243463 -1.06818954]
 [ 0.         -0.65921725 -0.31921998]
 [ 0.          0.          0.00820686]]


In [4]:
import numpy as np
A = np.random.rand(3,3)
A = np.dot(A,A.transpose())
B = np.linalg.cholesky(A)

print(A)
print()
print(B)
print()
print(np.transpose(B))

[[0.4470469  0.27235044 0.57176999]
 [0.27235044 0.94755864 0.43256804]
 [0.57176999 0.43256804 0.91287236]]

[[0.66861566 0.         0.        ]
 [0.40733483 0.88410236 0.        ]
 [0.85515496 0.09527589 0.41533705]]

[[0.66861566 0.40733483 0.85515496]
 [0.         0.88410236 0.09527589]
 [0.         0.         0.41533705]]
