# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.


## Numpy documentation ##
* NumPy: the absolute basics for beginners [🔗](https://numpy.org/doc/stable/user/absolute_beginners.html)
* NumPy fundamentals[🔗](https://numpy.org/devdocs/user/basics.html)

## Installation Instructions

in anaconda

    conda install numpy

in pip

    pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

: 

# Numpy Arrays




## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [197]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [198]:
np.array(my_list)

array([1, 2, 3])

In [199]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [200]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Replicating, joining, or mutating existing arrays


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
print(b)
b += 1
print('a =', a, '; b =', b)

: 

In this example, you did not create a new array. You created a variable, b that viewed the first 2 elements of a. When you added 1 to b you would get the same result by adding 1 to a[:2].
If you want to create a new array, use the numpy.copy array creation routine as such:

In [202]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


block matrix

In [203]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [204]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros , ones, diags

Generate arrays of zeros ,ones , diags

In [206]:
np.zeros(3)

array([0., 0., 0.])

In [207]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [208]:
np.ones(3)

array([1., 1., 1.])

In [209]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [210]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [211]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [212]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

### linspace
Return evenly spaced numbers over a specified interval.

In [213]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [214]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [215]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [216]:
np.random.rand(2)

array([0.65008792, 0.15796176])

In [217]:
np.random.rand(5,5)

array([[0.53721081, 0.82866655, 0.49005137, 0.78947197, 0.59328551],
       [0.93854472, 0.43179904, 0.24603807, 0.71924911, 0.5731642 ],
       [0.85694471, 0.08129493, 0.80515   , 0.66835401, 0.49360263],
       [0.58741958, 0.62978339, 0.15584674, 0.33844519, 0.57578289],
       [0.51717045, 0.63757052, 0.04989296, 0.92948521, 0.08639838]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [218]:
np.random.randn(2)

array([-1.03442547,  0.21925424])

In [219]:
np.random.randn(5,5)

array([[ 0.22260171,  1.75424593,  0.44034157,  0.30442882,  0.13292578],
       [ 0.1866668 ,  1.61738908, -0.38384671, -0.59525454, -1.30204065],
       [ 1.10421891,  0.80523781,  0.31072296,  2.32161894,  0.24936042],
       [ 0.16363741, -1.42194427,  1.73268589, -0.15712196, -0.23839214],
       [-0.24825614, -0.74153506,  0.0816    ,  0.95052835, -1.28945457]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [220]:
np.random.randint(1,100)

67

In [221]:
np.random.randint(1,100,10)

array([65,  4, 89, 30, 58, 71, 84, 92, 48, 18])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [222]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [223]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [224]:
ranarr

array([22, 15, 25,  7, 44, 33, 31, 13,  9, 35])

## Reshape, flatten 
Returns an array containing the same data with a new shape.

In [225]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [226]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [227]:
arr.shape

(25,)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [228]:
ranarr

array([22, 15, 25,  7, 44, 33, 31, 13,  9, 35])

In [229]:
ranarr.max()

44

In [230]:
ranarr.argmax()

4

In [231]:
ranarr.min()

7

In [232]:
ranarr.argmin()

3

## Shape

Shape is an attribute that arrays have (not a method):

In [233]:
# Vector
arr.shape

(25,)

In [234]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [235]:
arr.reshape(1,25).shape

(1, 25)

In [236]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [237]:
arr.reshape(25,1).shape

(25, 1)

### dtype ###

reference 
* overview (🔗)['https://numpy.org/devdocs/user/basics.types.html']
* dtypes (🔗)['https://numpy.org/devdocs/reference/arrays.dtypes.html#arrays-dtypes']

You can also grab the data type of the object in the array:




In [238]:
arr_dtype = np.arange(0,20,2, dtype=float)
print(arr_dtype)
arr_dtype.dtype

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


dtype('float64')

In [239]:
arr.dtype

dtype('int32')

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [240]:
import numpy as np
arr = np.arange(0,10)
arr2 = np.arange(0,20,2) 
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


In [241]:
arr + arr2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [242]:
arr2 * arr

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

In [243]:
arr2 - arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [244]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr2/arr

C:\Users\gurup\AppData\Local\Temp\ipykernel_8876\209023188.py:3: RuntimeWarning: invalid value encountered in divide
  arr2/arr


array([nan,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [245]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\gurup\AppData\Local\Temp\ipykernel_8876\1360216608.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [246]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [247]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [248]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [249]:
np.max(arr) #same as arr.max()

9

In [250]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [251]:
np.log(arr)

C:\Users\gurup\AppData\Local\Temp\ipykernel_8876\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [252]:
#Creating sample array
arr1 = np.arange(0,11)

In [253]:
#Show
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [254]:
#Get a value at an index
arr1[8]

8

In [255]:
#Get values in a range
arr1[1:5]

array([1, 2, 3, 4])

In [256]:
#Get values in a range
arr1[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [257]:
#Setting a value with index range (Broadcasting)
arr1[0:5]=100

#Show
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [258]:
# Reset array, we'll see why I had to reset in  a moment
arr1 = np.arange(0,11)

#Show
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [259]:
#Important notes on Slices
slice_of_arr1 = arr1[0:6]

#Show slice
slice_of_arr1

array([0, 1, 2, 3, 4, 5])

In [260]:
#Change Slice
slice_of_arr1[:]=99

#Show Slice again
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [261]:
arr1

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [262]:
#To get a copy, need to be explicit
arr1_copy = arr1.copy()

arr1_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [263]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [264]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [265]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [266]:
# Getting individual element value
arr_2d[1,0]

20

In [267]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [268]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [269]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [270]:
#Set up matrix
arr2d = np.zeros((10,10))

In [271]:
#Length of array
arr_length = arr2d.shape[1]

In [272]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [273]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [274]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [275]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [276]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [277]:
bool_arr = arr>4

In [278]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [279]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [280]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [281]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Matrix Operations

https://www.programiz.com/python-programming/numpy/matrix-operations#google_vignette

https://numpy.org/doc/stable/reference/routines.linalg.html

numpy has own sub package called linalg for  handeling the linear algebra

In [282]:
# create a 2x2 matrix
matrix1 = np.array([[1, 3],
                   [5, 7]])

print("2x2 Matrix:\n",matrix1)

# create a 3x3  matrix
matrix2 = np.array([[2, 3, 5],
             	    [7, 14, 21],
                    [1, 3, 5]])

print("\n3x3 Matrix:\n",matrix2)

2x2 Matrix:
 [[1 3]
 [5 7]]

3x3 Matrix:
 [[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


Perform Matrix Multiplication

In [283]:
# create two matrices
matrix1 = np.array([[1, 3],
             		[5, 7]])

matrix2 = np.array([[2, 6],
                    [4, 8]])

# calculate the dot product of the two matrices
result = np.dot(matrix1, matrix2)

print("matrix1 x matrix2: \n",result)
print("matrix1 x matrix2: \n",matrix1@matrix2)

matrix1 x matrix2: 
 [[14 30]
 [38 86]]
matrix1 x matrix2: 
 [[14 30]
 [38 86]]


Transpose NumPy Matrix

In [284]:
matrix1 = np.array([[1, 3, 2],
             		[5, 7, 9]])

# get transpose of matrix1
result = np.transpose(matrix1)
print(matrix1)
print("--------------------------")
print(result)
print(matrix1.T)
print("--------------------------`")

[[1 3 2]
 [5 7 9]]
--------------------------
[[1 5]
 [3 7]
 [2 9]]
[[1 5]
 [3 7]
 [2 9]]
--------------------------`


 Inverse of a Matrix in NumPy

In [285]:
# create a 3x3 square matrix
matrix1 = np.array([[1, 3, 5],
             		[7, 9, 2],
                    [4, 6, 8]])

# find inverse of matrix1
print(matrix1)

print()
result = np.linalg.inv(matrix1)

print(result)

[[1 3 5]
 [7 9 2]
 [4 6 8]]

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


Determinant of a Matrix in NumPy

In [286]:
import numpy as np

# create a matrix
matrix1 = np.array([[1, 2, 3],
             		[4, 5, 1],
                    [2, 3, 4]])

# find determinant of matrix1
result = np.linalg.det(matrix1)

print(result)

-5.000000000000001
